sequenceDiagram
    actor u as Users
    participant fe as Front-End (react native)
    participant cs as CoinService
    participant cg as CoinGeckoAPI
    u ->> fe: open coin rate menu
    fe ->> cs: HTTP_Request (GET) /coin-rate
    cs ->> cg : HTTP_Request (GET) api.coingecko.com/api/v3/exchange_rates 
    note right of cg: exchange rate
    cg -->> cs: JSON
    cs ->> cs: decoding JSON
    cs ->> cs: custom response by add new field key "name", value ="Rafael Nadal"
    cs -->> fe: display that new field value
    fe -->> u: coin rate menu with Rafael Nadal on top of menu